-- MySQL Workbench Synchronization
-- Generated: 2021-02-19 15:31
-- Model: New Model
-- Version: 1.0
-- Project: Name of the project
-- Author: Audrey

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

CREATE SCHEMA IF NOT EXISTS `portfolio-cv` DEFAULT CHARACTER SET utf8 ;

CREATE TABLE IF NOT EXISTS `portfolio-cv`.`user` (
  `idUser` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `loginUser` VARCHAR(80) NOT NULL,
  `pwdUser` VARCHAR(255) NOT NULL,
  `mailUser` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `portfolio-cv`.`projects` (
  `idProjects` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `titleProjects` VARCHAR(80) NOT NULL,
  `descProjects` TINYTEXT NOT NULL,
  `urlProjects` VARCHAR(255) NOT NULL,
  `imgNameProjects` VARCHAR(255) NOT NULL,
  `altImgProjects` VARCHAR(100) NOT NULL,
  `titleImgProjects` VARCHAR(50) NOT NULL,
  `user_idUser` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`idProjects`, `user_idUser`),
  INDEX `fk_projects_user_idx` (`user_idUser` ASC) VISIBLE,
  CONSTRAINT `fk_projects_user`
    FOREIGN KEY (`user_idUser`)
    REFERENCES `portfolio-cv`.`user` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
